name: xl_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #-----
  just_audio: ^0.7.4
  audio_session: ^0.1.0 #配合 音乐播放器使用 也可单独使用
  audio_service: ^0.17.0 #配合 音乐播放器使用 也可单独使用
  #-----
  rxdart: ^0.26.0
  flutter_cache_manager: ^3.0.1
  scroll_to_index: ^2.0.0
  charcode: ^1.2.0
  photo_view: ^0.11.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  # 高级扩展 类似把dart变成kotlin那里舒适
  supercharged: ^2.0.0
  flash: ^1.5.1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  wave: ^0.2.0
  sliver_tools: ^0.2.1
  keyboard_actions: ^3.4.0
  flutter_downloader: ^1.6.0 #支持空安全
  # sqflite: ^1.3.00
  # permission_handler: ^6.1.1 #权限管理
  animations: ^2.0.0 #强大的动画库
  simple_animations: ^3.0.3 #简单的小部件动画-but it not simple
  dio: ^4.0.0 # network request frame 
  flutter_sticky_header: ^0.6.0
  # no sql
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  get: ^4.1.4
  flutter_slidable: ^0.6.0
  file_picker: ^3.0.1
  translator: ^0.1.6+1  # 基于 google 翻译 api
  line_icons: ^2.0.1
  flutter_advanced_progress: ^1.0.0+1
  logger: ^1.0.0
  connectivity: ^3.0.3 #网络请求
  fluro: ^2.0.3
  # print_color: ^2.2.7
  # whatsapp_unilink: ^2.0.0
  mockito: ^5.0.5 #模拟数据
  pull_to_refresh: ^2.0.0
  hooks_riverpod: ^0.14.0+4
  flutter_native_timezone: ^2.0.0
  timezone: ^0.7.0
  encrypt: ^5.0.0
  url_launcher: ^6.0.9
  flutter_local_notifications: ^8.0.0
  device_info: ^2.0.2
  getwidget: ^2.0.3
  permission_handler: ^8.1.4+2




dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
  

flutter:

  uses-material-design: true
  assets:
    - assets/qdy.jpg
  